version: appveyor.{build}

init:
  - cmd: git config --global core.autocrlf true
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\yarp

platform:
  - Win32
#  - x64

configuration:
  - Release
  - Debug

branches:
  except:
    - travis

install:
  - cmd: md C:\downloads

  # Get 7zip
  - cmd: cinst 7zip.commandline -x86


  # Get ACE:
  - cmd: if "%platform%"=="Win32" appveyor DownloadFile "http://www.icub.org/download/packages/windows/msvc11/ACE_6.1.0-bin-msvc11.zip" -FileName "C:\downloads\ace.zip"
  - cmd: 7z x C:\downloads\ace.zip -oC:\tools\ACE -y > nul
  - cmd: set ACE_ROOT=C:\tools\ACE\ACE_wrappers
  - cmd: set PATH=%PATH%;C:\tools\ACE\ACE_wrappers\bin;C:\projects\yarp\build\bin\%CONFIGURATION%;C:\projects\yarp\build\lib\%CONFIGURATION%

  # Get Eigen:
  - cmd: appveyor DownloadFile "http://bitbucket.org/eigen/eigen/get/3.3-beta2.zip" -FileName "C:\downloads\eigen.zip"
  - cmd: 7z x C:\downloads\eigen.zip -o"C:\tools\eigen" -y > nul
  - cmd: set EIGEN3_ROOT=C:\tools\eigen\eigen-eigen-69d418c06999

  # Get Qt5:
  - cmd: appveyor DownloadFile "https://raw.githubusercontent.com/robotology-dependencies/robotology-dep-scripts/master/qt5/qt-installer-noninteractive.qs" -FileName "C:\downloads\qt-installer-noninteractive.qs"
  - cmd: if "%platform%"=="Win32" appveyor DownloadFile "https://download.qt.io/official_releases/qt/5.5/5.5.1/qt-opensource-windows-x86-msvc2012-5.5.1.exe" -FileName "C:\downloads\qt5.exe"
  - cmd: if "%platform%"=="Win32" C:\downloads\qt5.exe --script C:\downloads\qt-installer-noninteractive.qs
  - cmd: if "%platform%"=="Win32" set QTDIR=C:\Qt\Qt5.5.1\5.5\msvc2012
  - cmd: set Qt5_DIR=%QTDIR%\lib\cmake\Qt5

before_build:
  - cmd: md C:\projects\yarp\build
  - cmd: cd C:\projects\yarp\build
  - cmd: if "%platform%"=="Win32" cmake -G"Visual Studio 11" -DCMAKE_INSTALL_PREFIX:PATH=C:\projects\yarp\install -C ..\scripts\admin\initial-cache.cmake ..
  - cmd: if "%platform%"=="x64" cmake -G"Visual Studio 11 Win64" -DCMAKE_INSTALL_PREFIX:PATH=C:\projects\yarp\install -C ..\scripts\admin\initial-cache.cmake ..

build:
  project: C:\projects\yarp\build\yarp.sln

after_build:
  - cmd: cmake --build C:\projects\yarp\build --target INSTALL --config %CONFIGURATION%

test_script:
  - cmd: set YARP_VERBOSE=1
  - cmd: set YARP_DATA_DIRS=C:\projects\yarp\build\share\yarp
  - cmd: ctest --output-on-failure --build . -C %CONFIGURATION%
