version: appveyor.{build}

platform:
  #- Win32
  - x64

os:
 - Visual Studio 2017
 - Visual Studio 2019

configuration:
  - Release
  #- Debug

branches:
  except:
    - /^.*travis.*$/
    - /^devel$/

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  CTEST_PARALLEL_LEVEL: 1
  YARP_VERBOSE: 1

init:
  - cmd: git config --global core.autocrlf true

  # System related variables
  - cmd: set CMAKE_GENERATOR=Visual Studio
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR=%CMAKE_GENERATOR% 15 2017
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set CMAKE_GENERATOR=%CMAKE_GENERATOR% 16 2019
  - cmd: echo CMAKE_GENERATOR=%CMAKE_GENERATOR%

  - cmd: set CMAKE_PLATFORM=%Platform%
  - cmd: echo CMAKE_PLATFORM=%CMAKE_PLATFORM%

  - cmd: set TIMEOUT=%SystemRoot%\System32\timeout.exe

  # Dependencies found in robotology-superbuild-dependencies and YCM packages.
  - cmd: set ROBOTOLOGY_SUPERBUILD_DEPENDENCIES_LATEST=0.4.0
  - cmd: set ROBOTOLOGY_SUPERBUILD_DEPENDENCIES_LATEST_TAG=v%ROBOTOLOGY_SUPERBUILD_DEPENDENCIES_LATEST%
  - cmd: set PATH=%PATH%;C:\robotology\vcpkg\installed\x64-windows\bin;C:\robotology\vcpkg\installed\x64-windows\debug\bin

  - cmd: set YCM_LATEST=0.12.0
  - cmd: set YCM_LATEST_TAG=v%YCM_LATEST%
  - cmd: set YCM_DIR=C:\robotology\YCM-%YCM_LATEST%-all

  # Installers URLs
  - cmd: set ROBOTOLOGY_SUPERBUILD_DEPENDENCIES_INSTALLER=https://github.com/robotology-playground/robotology-superbuild-dependencies/releases/download/%ROBOTOLOGY_SUPERBUILD_DEPENDENCIES_LATEST_TAG%/vcpkg-robotology.zip
  - cmd: set YCM_INSTALLER=https://github.com/robotology/ycm/releases/download/%YCM_LATEST_TAG%/YCM-%YCM_LATEST%-all.tar.gz

  # Prepare YARP for tests
  - cmd: set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\build\bin\%CONFIGURATION%
  - cmd: set YARP_DATA_DIRS=%APPVEYOR_BUILD_FOLDER%\build\share\yarp

  # Print some useful informations:
  - cmd: set
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: md C:\downloads

  # Get Robotology Superbuild Dependencies
  - cmd: echo Downloading %ROBOTOLOGY_SUPERBUILD_DEPENDENCIES_INSTALLER%
  - cmd: appveyor DownloadFile "%ROBOTOLOGY_SUPERBUILD_DEPENDENCIES_INSTALLER%" -FileName "C:\downloads\vcpkg-robotology.zip"
  - cmd: 7z x -oC:\ "C:\downloads\vcpkg-robotology.zip" > nul

  # Get YCM installer
  - cmd: echo Downloading %YCM_INSTALLER%
  - cmd: appveyor DownloadFile "%YCM_INSTALLER%" -FileName "C:\downloads\ycm.tar.gz"
  - cmd: 7z x "C:\downloads\ycm.tar.gz" -so | 7z x -si -ttar -oC:\robotology > nul

before_build:
  - cmd: cmake -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%\build -G"%CMAKE_GENERATOR%" -A%CMAKE_PLATFORM% -DCMAKE_INSTALL_PREFIX:PATH=%APPVEYOR_BUILD_FOLDER%\install -C%APPVEYOR_BUILD_FOLDER%\.ci\initial-cache.appveyor.cmake -DCMAKE_TOOLCHAIN_FILE=C:/robotology/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: build\yarp.sln
  parallel: false
  verbosity: minimal

after_build:
  - cmd: cmake --build %APPVEYOR_BUILD_FOLDER%\build --target PACKAGE --config %CONFIGURATION%
  - cmd: move /Y %APPVEYOR_BUILD_FOLDER%\build\*.exe %APPVEYOR_BUILD_FOLDER%

test_script:
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" cmake --build %APPVEYOR_BUILD_FOLDER%\build --target RUN_TESTS --config %CONFIGURATION%

notifications:
  - provider: Slack
    incoming_webhook:
      secure: y4pfqod7KJ2iS3k3TbRPSpZ17uNnIPWIWgH79GirKA3xJfIcbvNhB/+mpBbClSXspVaFuPDr19gFj7aBGmoLBhR1DIXAzPDoYonYYpEZdF4=

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
