sudo: required
dist: trusty
language: cpp

cache:
  ccache: true

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    - TRAVIS_BUILD_TYPE=Release
    - TRAVIS_WITH_INTEGRATION_TESTS=false
    - TRAVIS_WITH_ACE=true
    - TRAVIS_STATIC=false
    - TRAVIS_CLEAN_API=false
    - TRAVIS_WITH_VALGRIND=false
    - TRAVIS_NO_DEPRECATED=false
    - TRAVIS_WITH_BROKEN_TESTS=false

  matrix:
    # Normal build
    - TRAVIS_WITH_CXX11=false
    # C++11 build
    - TRAVIS_WITH_CXX11=true

matrix:
  exclude:
  - os: osx
    compiler: gcc

  include:
    # No ACE build  (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=false

    # No ACE build  (linux, clang)
    - os: linux
      compiler: clang
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=false

    # C++11, no ACE build  (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=true

    # C++11, no ACE build  (linux, clang)
    - os: linux
      compiler: clang
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=true

    # Normal build with CLEAN_API (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_CXX11=false TRAVIS_CLEAN_API=true

    # Normal build with CLEAN_API (linux, clang)
    - os: linux
      compiler: clang
      env: TRAVIS_WITH_CXX11=false TRAVIS_CLEAN_API=true

    # Normal build with Ninja generator (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_CXX11=false TRAVIS_CMAKE_GENERATOR="Ninja"

    # Normal build with Ninja generator (linux, clang)
    - os: linux
      compiler: clang
      env: TRAVIS_WITH_CXX11=false TRAVIS_CMAKE_GENERATOR="Ninja"

    # Normal build no deprecated (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_CXX11=false TRAVIS_NO_DEPRECATED=true

    # Normal build no deprecated (linux, clang)
    - os: linux
      compiler: clang
      env: TRAVIS_WITH_CXX11=false TRAVIS_NO_DEPRECATED=true

    # Static build (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_CXX11=false TRAVIS_STATIC=true

    # Static build (linux, clang)
    - os: linux
      compiler: clang
      env: TRAVIS_WITH_CXX11=false TRAVIS_STATIC=true

    # Static build, no ACE (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=false TRAVIS_STATIC=true

    # Static build, no ACE (linux, clang)
    - os: linux
      compiler: clang
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=false TRAVIS_STATIC=true

    # Normal build with valgrind (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_CXX11=false TRAVIS_WITH_VALGRIND=true

    # C++11 build with valgrind (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_CXX11=true TRAVIS_WITH_VALGRIND=true

    # No ACE build with valgrind (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=false TRAVIS_WITH_VALGRIND=true

    # C++11 build with valgrind (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_ACE=false TRAVIS_WITH_CXX11=true TRAVIS_WITH_VALGRIND=true

    # Normal build with Xcode 7.3 (osx, clang)
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: TRAVIS_WITH_CXX11=false TRAVIS_CMAKE_GENERATOR="Xcode"

    # C++11 build with Xcode 7.3 (osx, clang)
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: TRAVIS_WITH_CXX11=true TRAVIS_CMAKE_GENERATOR="Xcode"

    # Normal build with Xcode 8 (osx, clang)
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: TRAVIS_WITH_CXX11=false TRAVIS_CMAKE_GENERATOR="Xcode"

    # C++11 build with Xcode 8 (osx, clang)
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: TRAVIS_WITH_CXX11=true TRAVIS_CMAKE_GENERATOR="Xcode"

    # Normal build with valgrind and broken tests (linux, gcc)
    - os: linux
      compiler: gcc
      env: TRAVIS_WITH_CXX11=false TRAVIS_WITH_VALGRIND=true TRAVIS_WITH_BROKEN_TESTS=true

    # Normal build with Coverage (linux, gcc)
#    - os: linux
#      compiler: gcc
#      env: TRAVIS_WITH_CXX11=false TRAVIS_BUILD_TYPE=Profile

    # Normal build with integration tests (linux, gcc)
#    - os: linux
#      compiler: gcc
#      env: TRAVIS_WITH_CXX11=false TRAVIS_WITH_INTEGRATION_TESTS=true

    # Normal build with integration tests (linux, clang)
#    - os: linux
#      compiler: clang
#      env: TRAVIS_WITH_CXX11=false TRAVIS_WITH_INTEGRATION_TESTS=true


  allow_failures:
    # Normal build with valgrind and broken tests (tests of already broken things)
    - env: TRAVIS_WITH_CXX11=false TRAVIS_WITH_VALGRIND=true TRAVIS_WITH_BROKEN_TESTS=true

    # Normal build with integration tests (sometimes integration::rpc test fails)
#    - env: TRAVIS_WITH_CXX11=false TRAVIS_WITH_INTEGRATION_TESTS=true


branches:
  except:
    - /^.*appveyor.*$/

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://packages.ros.org/ros/ubuntu trusty main'
        key_url: 'http://packages.ros.org/ros.key'
    packages:
      - ninja-build
      - lcov
      - valgrind
      - ccache
      - libace-dev
      - libsqlite3-dev
      - libtinyxml-dev
      - libedit-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtmultimedia5-dev
      - libqt5opengl5-dev
      - libgsl0-dev
      - libqcustomplot-dev
      - libopencv-dev
      - libeigen3-dev

notifications:
  irc:
    channels:
      - "chat.freenode.net#yarpers"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    use_notice: true
    skip_join: true
  slack:
    rooms:
      - icub-facility:4meEzvbWZHS4z8oAStah5c6R#yarp

before_install:
  # Prepare ros environment variables
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then export ROS_CI_DESKTOP=`lsb_release -cs`; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then export ROS_CI_VERSION=jade; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then export ROS_CI_PREFIX=ros-${ROS_CI_VERSION}-; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then export ROS_HOSTNAME=localhost; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then export ROS_MASTER_URI=http://localhost:11311; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then export ROBOT=sim; fi; fi

  # Update repositories (macOS)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

  # Add additional repositories
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi

  # Install ccache on osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ccache; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

  # Use ccache also for clang and clang++ on linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CC" == "clang" ]; then sudo ln -s ../../bin/ccache /usr/lib/ccache/clang; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CC" == "clang" ]; then export CFLAGS="$CFLAGS -Qunused-arguments"; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "clang++" ]; then sudo ln -s ../../bin/ccache /usr/lib/ccache/clang++; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "clang++" ]; then export CXXFLAGS="$CXXFLAGS -Qunused-arguments"; fi; fi

  # Print some more system information after installing all build tools
  - echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
  - uname -a
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then lsb_release -a; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then system_profiler SPSoftwareDataType; fi
  - env
  - which cmake
  - cmake --version
  - which $CC
  - $CC --version
  - which $CXX
  - $CXX --version
  - which ccache
  - ccache --version
  - ccache -s
  - echo "--------------------  END SYSTEM INFORMATION  --------------------"


install:
  # Install ACE
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then if $TRAVIS_WITH_ACE; then brew install ace; fi; fi

  # Install other core dependencies (sqlite, tinyxml, libedit)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sqlite tinyxml homebrew/dupes/libedit; fi

  # Install Qt5 GUIs dependencies
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export Qt5_DIR="/usr/local/opt/qt5/lib/cmake/Qt5"; fi

  # Install GPL dependencies (gsl, qcustomplot)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gsl readline; fi

  # Install other dependencies (opencv, eigen)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip uninstall numpy || true; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install opencv eigen; fi

  # Install swig stuff
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then sudo apt-get -y install liblua5.1-0-dev lua5.1 tcl-dev tk-dev mono-mcs; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then wget https://github.com/robotology-dependencies/swigs/releases/download/v0.0.5/swigs.zip; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then unzip -q swigs.zip; mkdir -p cache; mv swigs cache/swig; fi; fi

  # Install ros stuff
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then sudo apt-get -y install ${ROS_CI_PREFIX}desktop-full; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then sudo rosdep init && rosdep update; fi; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if $TRAVIS_WITH_INTEGRATION_TESTS; then source /opt/ros/${ROS_CI_VERSION}/setup.bash; fi; fi


before_script:
  # Prepare build directory
  - mkdir -p build
  - if $TRAVIS_WITH_INTEGRATION_TESTS; then ln -s ../cache build/cache; fi

  # Prepare cmake options
  - . scripts/admin/generate-cmake-options.sh $(hostname) $(lsb_release -cs) continuous
  - export YARP_CMAKE_OPTIONS=" $CMAKE_OPTIONS"
  - if ! $TRAVIS_WITH_ACE; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DSKIP_ACE=ON -DYARP_TEST_HEAP=ON"; fi
  - if $TRAVIS_WITH_CXX11; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DYARP_EXPERIMENTAL_CXX11=ON"; fi
  - if $TRAVIS_WITH_INTEGRATION_TESTS; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DYARP_TEST_INTEGRATION=ON"; fi
  - if $TRAVIS_STATIC; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DCREATE_SHARED_LIBRARY=OFF"; fi
  - if $TRAVIS_CLEAN_API; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DYARP_CLEAN_API=ON -DYARP_COMPILE_TESTS=OFF"; fi
  - if $TRAVIS_WITH_VALGRIND; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DYARP_VALGRIND_TESTS=ON -DYARP_VALGRIND_DRD_TESTS=OFF -DYARP_VALGRIND_HELGRIND_TESTS=OFF YARP_VALGRIND_MEMCHECK_TESTS=ON YARP_VALGRIND_SGCHECK_TESTS=OFF"; fi
  - if $TRAVIS_NO_DEPRECATED; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DYARP_NO_DEPRECATED=ON"; fi
  - if $TRAVIS_WITH_BROKEN_TESTS; then export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DYARP_ENABLE_BROKEN_TESTS=ON"; fi
  - export YARP_CMAKE_OPTIONS="${YARP_CMAKE_OPTIONS} -DCREATE_LIB_MATH_USING_GSL=OFF"

  # Print cmake flags
  - echo "--------------------     BEGIN CMAKE FLAGS    --------------------"
  - echo -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ${YARP_CMAKE_OPTIONS}
  - echo "--------------------      END CMAKE FLAGS     --------------------"

  # Run CMake
  - (cd build; cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ${YARP_CMAKE_OPTIONS} ..)

  # Print cmake cache
  - echo "--------------------     BEGIN CMAKE CACHE    --------------------"
  - (cd build; cat CMakeCache.txt)
  - echo "--------------------      END CMAKE CACHE     --------------------"

  # Reset coverage information
  - if [ "$TRAVIS_BUILD_TYPE" == "Profile" ]; then (cd build; lcov --directory . --zerocounters); fi


script:
  # Build yarp
  - (cd build; cmake --build . --config ${TRAVIS_BUILD_TYPE})

  # Configure yarp
  - if $TRAVIS_WITH_INTEGRATION_TESTS; then build/bin/yarp conf 0 0 local; fi

  # Run unit tests
  - if ! $TRAVIS_CLEAN_API; then (cd build; travis_wait 50 ctest --output-on-failure --build . -C ${TRAVIS_BUILD_TYPE}); fi

  # Test installation
  - (cd build; sudo cmake --build . --config ${TRAVIS_BUILD_TYPE} --target install)

  # Build also the os examples
  - mkdir example/os/build
  - (cd example/os/build; cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..)
  - (cd example/os/build; cmake --build . --config ${TRAVIS_BUILD_TYPE})


after_success:
  # Capture coverage info for Profile builds
  - if [ "$TRAVIS_BUILD_TYPE" == "Profile" ]; then (cd build; lcov --directory . --capture --output-file coverage.info); fi
  # Filter out system and test code
  - if [ "$TRAVIS_BUILD_TYPE" == "Profile" ]; then (cd build; lcov --remove coverage.info '/usr/*' 'tests/*' 'example/*' 'extern/*' 'idls/*' '*/harness/*' 'yarp/build/*' 'src/libYARP_serversql/*' 'src/libYARP_name/*' --output-file coverage.info); fi
  # Debug before upload
  - if [ "$TRAVIS_BUILD_TYPE" == "Profile" ]; then (cd build; lcov --list coverage.info); fi
  # Uploads to coveralls
  - if [ "$TRAVIS_BUILD_TYPE" == "Profile" ]; then (cd build; coveralls-lcov --source-encoding=ISO-8859-1 coverage.info); fi
