language: cpp
compiler:
  - gcc
  - clang
env:
  - TRAVIS_WITH_ACE=true CMAKE_FLAGS=
  - TRAVIS_WITH_ACE=false CMAKE_FLAGS="-DSKIP_ACE=TRUE"
before_install:
  - sudo apt-get update
install:
  - if $TRAVIS_WITH_ACE; then sudo apt-get install libace-dev; fi
script: cmake $CMAKE_FLAGS . && make && make test
