name: 'License Check'

on:
  push:
  pull_request:

jobs:
  check-license:
    name: 'Check License'

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq -y perl

    - name: Check License
      run: |
        tests/misc/check_license.pl
