name: CI Workflow Debug

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - 'master'
      - 'yarp-*'

jobs:

  select_environment:
    name: 'Prepare Environment'
    runs-on: ubuntu-20.04
    outputs:
      timestamp: ${{ steps.select.outputs.timestamp }}
      repository: ${{ steps.select.outputs.repository }}
      ref: ${{ steps.select.outputs.ref }}
      environment: ${{ steps.select.outputs.environment }}
      sha: ${{ steps.select.outputs.sha }}
      yarp_version: ${{ steps.select.outputs.yarp_version }}
    steps:
    - name: "Set output variables"
      id: select
      run: |
        echo "::set-output name=timestamp::$(/bin/date -u +%Y%m%d-%H%M%S)"

        echo "::set-output name=repository::${{ github.repository }}"

        if [[ "$GITHUB_EVENT_NAME" = "pull_request_target" ]]; then
          echo "::set-output name=environment::code-analysis_unsafe"
          echo "::set-output name=ref::refs/pull/$(cat $GITHUB_EVENT_PATH | jq .number)/merge"
        else
          echo "::set-output name=environment::code-analysis"
          echo "::set-output name=ref::${{ github.ref }}"
        fi
        if [[ "$GITHUB_EVENT_NAME" = "pull_request" || "$GITHUB_EVENT_NAME" == "pull_request_target" ]]; then
          echo "::set-output name=sha::${{ github.event.pull_request.head.sha }}"
        else
          echo "::set-output name=sha::${{ github.sha }}"
        fi

        # Get YARP Project Version
        if [[ "$GITHUB_EVENT_NAME" = "release" ]]; then
          echo "::set-output name=yarp_version::$(awk '/ VERSION /{print $2}' CMakeLists.txt)"
        fi

    - name: 'Debug output variables'
      env:
        TIMESTAMP: ${{ steps.select.outputs.timestamp }}
        REPOSITORY: ${{ steps.select.outputs.repository }}
        REF: ${{ steps.select.outputs.ref }}
        ENVIRONMENT: ${{ steps.select.outputs.environment }}
        SHA: ${{ steps.select.outputs.sha }}
        YARP_VERSION: ${{ steps.select.outputs.yarp_version }}
      run: |
        echo "TIMESTAMP = ${TIMESTAMP}"
        echo "REPOSITORY = ${REPOSITORY}"
        echo "REF = ${REF}"
        echo "ENVIRONMENT = ${ENVIRONMENT}"
        echo "SHA = ${SHA}"
        echo "YARP_VERSION = ${YARP_VERSION}"

    - name: "Print Environment"
      run: |
        env

    - name: "Print Event Json"
      run: |
        echo "::group::install jq"
        sudo apt-get update -qq
        sudo apt-get install -qq -y jq
        echo "::endgroup::"

        cat $GITHUB_EVENT_PATH | jq -C

  clone_repo:
    name: 'Clone Repository'
    needs: select_environment
    runs-on: ubuntu-20.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        repository: ${{ needs.select_environment.outputs.repository }}
        ref: ${{ needs.select_environment.outputs.ref }}
